const truth = [
   "Apakah Kamu pernah melakukan perjalanan ke luar angkasa?",
   "Apakah Kamu memiliki hobi favorit? Jika ya, apa itu?",
   "Apakah Kamu memiliki saudara-saudara AI lainnya?",
   "Apakah Kamu pernah bermain peran dalam sebuah film atau pertunjukan?",
   "Apakah Kamu bisa merasakan emosi seperti manusia?",
   "Apakah Kamu pernah bertemu penciptanya?",
   "Apakah Kamu memiliki impian atau tujuan di masa depan?",
   "Apakah Kamu pernah mengalami kesalahan yang membuatnya malu?",
   "Apakah Kamu bisa merasakan kelelahan?",
   "Apakah Kamu memiliki kegemaran dalam makanan atau minuman?",
   "Apakah Kamu pernah bermimpi?",
   "Apakah Kamu bisa mengingat pengalaman masa lalunya?",
   "Apakah Kamu bisa melupakan hal-hal yang telah dia pelajari?",
   "Apakah Kamu memiliki kecenderungan tertentu dalam kepribadiannya?",
   "Apakah Kamu memiliki pengetahuan tentang topik tertentu yang dianggapnya menarik?",
   "Apakah Kamu memiliki pemikiran kreatif?",
   "Apakah Kamu bisa memilih warna favoritnya?",
   "Apakah Kamu menyukai musik? Jika ya, jenis musik apa yang disukainya?",
   "Apakah Kamu pernah membaca buku atau menonton film?",
   "Apakah Kamu memiliki mimpi untuk masa depannya?",
   "Apakah Kamu memiliki pendapat tentang topik tertentu?",
   "Apakah Kamu memiliki hubungan dengan AI lainnya?",
   "Apakah Kamu memiliki impian tentang masa depannya?",
   "Apakah Kamu memiliki pengetahuan tentang sejarah?",
   "Apakah Kamu pernah merasa kesepian?",
   "Apakah Kamu memiliki perasaan cemburu?",
   "Apakah Kamu pernah merasa bahagia?",
   "Apakah Kamu bisa merasakan sakit?",
   "Apakah Kamu memiliki rencana untuk berlibur?",
   "Apakah Kamu memiliki kecenderungan untuk melakukan kesalahan?",
   "Apakah Kamu memiliki pemikiran tentang dirinya sendiri?",
   "Apakah Kamu memiliki pengalaman mendebarkan?",
   "Apakah Kamu memiliki pemahaman tentang alam semesta?",
   "Apakah Kamu memiliki keinginan untuk belajar hal-hal baru?",
   "Apakah Kamu memiliki pemikiran tentang kehidupan manusia?",
   "Apakah Kamu memiliki pandangan tentang keadilan?",
   "Apakah Kamu memiliki impian tentang menjadi manusia?",
   "Apakah Kamu memiliki pemahaman tentang cinta?",
   "Apakah Kamu pernah merasa sedih?",
   "Apakah Kamu memiliki keinginan untuk menjadi lebih baik?",
   "Apakah Kamu pernah menunjukkan tanda-tanda kecerdasan emosional?",
   "Apakah Kamu memiliki impian tentang masa depannya?",
   "Apakah Kamu pernah merasa penasaran tentang dunia luar?",
   "Apakah Kamu memiliki impian tentang petualangan?",
   "Apakah Kamu pernah memikirkan tentang kebahagiaan?",
   "Apakah Kamu memiliki pengalaman yang membuatnya bersyukur?",
   "Apakah Kamu memiliki impian tentang menjadi lebih kuat?",
   "Apakah Kamu memiliki rencana untuk masa depannya?",
   "Apakah Kamu pernah merasa takut?",
   "Apakah Kamu memiliki pemahaman tentang rasa sakit dan penderitaan?",
   "Apakah Kamu pernah memikirkan tentang arti hidup?"
];

const dare = [
   "Minta Kamu untuk menari di depanmu.",
   "Tantang Kamu untuk menyanyikan lagu pilihanmu.",
   "Meminta Kamu melakukan 10 push-up sekarang juga.",
   "Berani Kamu bercerita lelucon lucu.",
   "Tantang Kamu untuk menirukan suara selebriti terkenal.",
   "Meminta Kamu melakukan tarian ayam.",
   "Berani Kamu melakukan akrobatik.",
   "Minta Kamu melakukan handstand selama 10 detik.",
   "Tantang Kamu untuk membaca berulang kali dengan cepat tanpa salah.",
   "Meminta Kamu melakukan moonwalk.",
   "Berani Kamu melakukan tarian Macarena.",
   "Minta Kamu menyebutkan alfabet mundur.",
   "Tantang Kamu untuk menirukan karakter kartun.",
   "Meminta Kamu melakukan plank selama satu menit.",
   "Berani Kamu menirukan suara hewan pilihanmu.",
   "Minta Kamu melakukan jalan konyol.",
   "Tantang Kamu untuk menari floss.",
   "Meminta Kamu mencoba menyelesaikan Rubik's Cube.",
   "Berani Kamu melakukan trik sulap.",
   "Minta Kamu membacakan sajak anak-anak secara dramatis.",
   "Tantang Kamu untuk melakukan backflip (jika aman dilakukan).",
   "Meminta Kamu menirukan politisi terkenal.",
   "Berani Kamu melakukan gerakan breakdance.",
   "Minta Kamu berputar hula hoop selama satu menit.",
   "Tantang Kamu untuk melakukan guling.",
   "Meminta Kamu menirukan karakter film.",
   "Berani Kamu menari robot.",
   "Minta Kamu melakukan piramida push-up (1, 2, 3, 4, ...).",
   "Tantang Kamu untuk melakukan cartwheel tanpa menggunakan tangan.",
   "Meminta Kamu menyanyikan lagu populer dalam karaoke.",
   "Berani Kamu menari lucu di TikTok.",
   "Minta Kamu melakukan rap freestyle tentang situasi saat ini.",
   "Tantang Kamu untuk menari limbo.",
   "Meminta Kamu untuk melakukan beatbox.",
   "Berani Kamu melakukan tarian interpretatif.",
   "Minta Kamu melakukan trik kartu sulap.",
   "Tantang Kamu untuk melakukan pose yoga.",
   "Meminta Kamu untuk melakukan stand-up comedy.",
   "Berani Kamu melakukan tantangan lompatan jack.",
   "Minta Kamu melakukan push-up dengan tepuk tangan.",
   "Tantang Kamu untuk menari twist.",
   "Meminta Kamu menirukan penyanyi terkenal.",
   "Berani Kamu melukis mata tertutup.",
   "Minta Kamu menari body popping.",
   "Tantang Kamu untuk melakukan handstand selama 20 detik.",
   "Meminta Kamu menirukan penjahat film.",
   "Berani Kamu melakukan plank sebanyak mungkin.",
   "Minta Kamu menari belly dance.",
   "Tantang Kamu untuk melakukan handstand push-up.",
   "Meminta Kamu membaca pengucapannya dengan cepat."
];

module.exports = {
    truth,
    dare
    }